on:
  push:
    paths:
      - 'README.Rmd'
      - '**/README.Rmd'

name: Render README

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Learn the game
        run: "echo 'hello'"
      - name: Learn the game
        run: echo ${{ github.sha }}
      - name: Learn the game
        run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
      - name: Render Rmd files for real
        run: "git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs -I % Rscript -e 'rmarkdown::render(\"%\")'"
      - name: Render Rmd files
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs -I % echo "hello % how are you?"
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs -I % Rscript -e 'rmarkdown::render("%")'
      - name: Commit results
        run: |
          git status
          git add **/README.md **/README_files
          git commit -m 'Re-build Rmd files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
